name: MSHV Tests (x86-64)
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    
    timeout-minutes: 60
    name: Tests (x86-64)
    runs-on: 
    - self-hosted
    - INTEL
    
    steps:
      - uses: gamora12/cloud-hypervisor/.github/workflows/mshv_build.yaml
      - name: Run unit tests
        run: scripts/dev_cli.sh tests --unit 
     
      - name: Run integration tests
        timeout-minutes: 40
        run: scripts/dev_cli.sh tests --integration 

      - name: Run live-migration integration tests
        timeout-minutes: 20
        run: scripts/dev_cli.sh tests --integration-live-migration 

      - name: Skipping build for PR
        run: echo "Skipping build for PR"