name: MSHV Performance Metrics Tests (x86-64)
on: 
  workflow_dispatch:
jobs:
  infrasetup:
    uses: ./.github/workflows/mshv-infra.yaml
    with:
      RG_NAME: "PerformanceMetrics"
      DOM0_SKU: "Standard_D64s_v4"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      DOM0_USERNAME: ${{ secrets.DOM0_USERNAME }}
      DOM0_PASSWORD: ${{ secrets.DOM0_PASSWORD }}
      X86_SOURCE_PATH: ${{ secrets.X86_SOURCE_PATH }}
      MSHV_STORAGE_ACCOUNT_PATH: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

  run_tests:
    name: Performance Metrics Tests (x86-64)
    runs-on:
      - self-hosted
      - INTEL
    needs: infrasetup
    steps:

      - name: Az Login
        run: az login --identity --username ${{ secrets.CLIENT_ID }}
     
      - name: Run performance metrics tests
        run: |

          set -x
          echo "Retrieving VM Private IP address"

          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g aasthagit -n dom0_x86 -d --query privateIps -o tsv)
          if [ $? -ne 0 ]; then
           echo "Failed to retrieve private IP address"
           exit 1
          fi
          echo "Successfully retrieved private IP address"
          echo $PRIVATE_IP
          sshpass -p "${{ secrets.DOM0_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{secrets.DOM0_USERNAME}}"@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"

            sudo chown -R ${{secrets.DOM0_USERNAME}} cloud-hypervisor
            cd cloud-hypervisor

            # Use the MS Guest Kernel, MS HV Firmware, and MS OVMF Firmware

            sudo USE_MS_GUEST_KERNEL=YES USE_MS_HV_FW=YES USE_MS_OVMF_FW=YES ./scripts/dev_cli.sh tests --hypervisor mshv --metrics
          EOF

      - name: Delete Resource Group
        run: |

          # Cleanup & deletion of Resource Group
          # az group delete --name aasthagit --yes --no-wait
          # echo "Resource group deleted"