name: MSHV Build
on: 
  workflow_dispatch:
jobs:
  infrasetup:
    uses: ./.github/workflows/mshv-infra.yaml
    with:
      RG: "MSHVBuild"
      STORAGE_ACCOUNT: "mshvbuildstorage"
      DOM0_SKU: "Standard_d16s_v5"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      MSHV_STORAGE_ACCOUNT_PATH_BUILD: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH_BUILD }}
      MSHV_STORAGE_ACCOUNT_PATH_LIVEMIGRATION: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH_LIVEMIGRATION }} 
      MSHV_STORAGE_ACCOUNT_PATH_INTEGRATION: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH_INTEGRATION }}
      MSHV_STORAGE_ACCOUNT_PATH_PERFMETRICS: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH_PERFMETRICS }}
      DOM0_USERNAME: ${{ secrets.DOM0_USERNAME }}
      DOM0_PASSWORD: ${{ secrets.DOM0_PASSWORD }}
      ADO_GIT_URL: ${{ secrets.ADO_GIT_URL }}
      X86_SOURCE_PATH: ${{ secrets.X86_SOURCE_PATH }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    
  build:
    name: Build
    runs-on:
      - self-hosted
      - INTEL
    needs: infrasetup
    strategy:
      fail-fast: false
      matrix:
        RUNNER: 
         - 'INTEL-RUNNER-1'
        BUILD_CMD: 
         - 'cargo build'
         - 'cargo build --no-default-features --features "mshv,kvm"'
         - 'cargo build --no-default-features --features "mshv,kvm,sev_snp,igvm"'
         - 'cargo build --package vhost_user_net'
         - 'cargo build --package vhost_user_block'
    steps:

      - name: Az Login
        run: az login --identity --username ${{ secrets.CLIENT_ID }}

      - name: Build MSHV
        run: |

          set -x
          echo "Retrieving VM Private IP address"

          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g MSHVBuild -n dom0_x86 -d --query privateIps -o tsv)
          if [ $? -ne 0 ]; then
           echo "Failed to retrieve private IP address"
           exit 1
          fi
          echo "Successfully retrieved private IP address"
          echo $PRIVATE_IP
          sshpass -p "${{ secrets.DOM0_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{secrets.DOM0_USERNAME}}"@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"
            cargo --version
            sudo chown -R ${{secrets.DOM0_USERNAME}} cloud-hypervisor
            cd cloud-hypervisor

            # Build Cloud-Hypervisor
            echo "Building Cloud-Hypervisor"
            ${{matrix.BUILD_CMD}} --release
          EOF

      - name: Delete Resource Group
        run: |

          # Cleanup & deletion of Resource Group
          az group delete --name MSHVBuild --yes --no-wait
          echo "Resource group deleted"