name: MSHV Cloudhypervisor Build
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build MSHV Cloudhypervisor
    runs-on: 
      - self-hosted
      - INTEL
    strategy:
      fail-fast: false
      matrix:
          x86_64 cargo build:
          - RUNNER: 'INTEL-RUNNER-1'
          - BUILD_CMD: 'cargo build'
          x86_64 cargo build --no-default-features --features "mshv,kvm":
          - RUNNER: 'INTEL-RUNNER-1'
          - BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm"'
          x86_64 cargo build --no-default-features --features "mshv,kvm,sev_snp,igvm":
          - RUNNER: 'INTEL-RUNNER-1'
          - BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm,sev_snp,igvm"'
          x86_64 cargo build --package vhost_user_net:
          - RUNNER: 'INTEL-RUNNER-1'
          - BUILD_CMD: 'cargo build --package vhost_user_net'
          x86_64 cargo build --package vhost_user_block:
          - RUNNER: 'INTEL-RUNNER-1'
          - BUILD_CMD: 'cargo build --package vhost_user_block'
          aarch64 cargo build:
          - RUNNER: 'ARM-RUNNER-1'
          - BUILD_CMD: 'cargo build --all'
          aarch64 cargo build --package vhost_user_net:
          - RUNNER: 'ARM-RUNNER-1'
          - BUILD_CMD: 'cargo build --all --package vhost_user_net'
          aarch64 cargo build --package vhost_user_block:
          - RUNNER: 'ARM-RUNNER-1'
          - BUILD_CMD: 'cargo build --all --package vhost_user_block'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install & login to AZ CLI
        run: |

          sudo apt-get install -y azure-cli
          az login --identity --username 7c8b017a-68e5-486e-81c1-9dc09edbc986

      - name: Create Resource Group & Storage Account
        run: |

          locations = ["westus2" "westus3" "westeurope"]
          sku_to_check ="Standard_d16s_v5"

          for location in "${locations[@]}"; do
              echo "Checking $sku_to_check in $location..."
              available_skus=$(az vm list-sizes --location $location --query "[].name" -o tsv)
              
              if echo "$available_skus" | grep -q "$sku_to_check"; then
                  echo "$sku_to_check is available in $location"
                  
                  echo "Creating VM"
                  
              else
                  echo "$sku_to_check is not available in $location"
              fi

          az group create --name aasthagit --location westus2
          echo "Resource group created"
          az storage account create --name aastsamplestorage --resource-group aasthagit --location westus2 --sku Standard_LRS --allow-shared-key-access false
          echo "Storage account created"

      - name: Copy/Upload VHD to Azure Storage Account
        env: 
          STORAGE_ACCOUNT_PATH: ${{ secrets.MSHV_STORAGE_ACCOUNT_PATH }}
        run: |

          set -x
          STORAGE_PATH: ${{ secrets.X86_SOURCE_PATH}}
          DESTINATION_PATH: ${{ secrets.DESTINATION_PATH_X86}}
          VHD_NAME: 'x86.vhd'
          IMAGE_NAME: vhd-image-aarch64
          BLOB_SOURCE: https://aastsamplestorage.blob.core.windows.net/vhds/x86.vhd
          if [ ${{matrix.RUNNER}} == 'ARM-RUNNER-1']; then
            STORAGE_PATH: ${{ secrets.AARCH64_SOURCE_PATH}}
            DESTINATION_PATH: ${{ secrets.DESTINATION_PATH_AARCH64}}
            VHD_NAME: 'aarch64.vhd'
            IMAGE_NAME: vhd-image-x86
            BLOB_SOURCE: https://aastsamplestorage.blob.core.windows.net/vhds/aarch64.vhd
          fi 

          az login --identity --username 7c8b017a-68e5-486e-81c1-9dc09edbc986
          echo "Installing AzCopy"
          wget https://aka.ms/downloadazcopy-v10-linux
          tar -xvzf downloadazcopy-v10-linux
          export PATH=$PATH:$PWD/azcopy_linux_amd64_10.25.1
          
          azcopy login --identity
          azcopy copy "${SOURCE_PATH}" "${DESTINATION_PATH}"
          
          if [ $? -ne 0 ]; then
            echo "AzCopy Failed: VHD upload failed"
            exit 1
          fi
            echo "AzCopy Succeeded: VHD upload complete"

          echo "Creating Blob URL"
          blob_url=$(az storage blob url --auth-mode login --container-name vhds --account-name aastsamplestorage --name ${{VHD_NAME}} --output tsv)
          echo $blob_url

          echo "Creating Image"
          az image create --resource-group aasthagit --name ${{IMAGE_NAME}} --source ${{BLOB_SOURCE}} --os-type Linux --location westus2 --hyper-v-generation V2
          echo "Image created"

          az image wait --image-name vhd-image --resource-group aasthagit --exists
          echo "Image is available"
          
      - name: Create DOM0 VM 
        run: |

          DOM0_NAME: dom0_x86
          if [ ${{matrix.RUNNER}} == 'ARM-RUNNER-1']; then
            DOM0_NAME: dom0_aarch64
           
          fi 
          set -x
          vm_creation=$(az vm create --resource-group aasthagit --name ${{DOM0_NAME}} --subnet ${{ secrets.SUBNET_ID }} --size Standard_d16s_v5 --location westus2 --image vhd-image --os-disk-size-gb 512 --public-ip-sku Standard --storage-sku Premium_LRS --admin-username ${{ secrets.ADMIN_USERNAME }} --admin-password ${{ secrets.ADMIN_PASSWORD }} --public-ip-address "")
          if [ $? -ne 0 ]; then
            echo "VM Creation Failed"
            exit 1
          fi
            echo "VM Creation Succeeded"
          echo $vm_creation
          
          echo "Retrieving VM Private IP address"

          # Get Private IP Address
          PRIVATE_IP=$(az vm show -g aasthagit -n ${{DOM0_NAME}} -d --query privateIps -o tsv)

          if [ $? -ne 0 ]; then
            echo "Failed to retrieve private IP address"
            exit 1
          fi
            echo "Successfully retrieved private IP address"

          echo $PRIVATE_IP
          echo "Installing sshpass"
          sudo apt install sshpass -y

          echo "Removing the old host key"
          ssh-keygen -R $PRIVATE_IP

          echo "SSH into the VM"
          sshpass -p "${{ secrets.DOM0_PASSWORD }}" ssh -o StrictHostKeyChecking=no cloud@$PRIVATE_IP << EOF
            set -x
            echo "Logged in"

            # Install Dependencies
            sudo tdnf install git moby-engine moby-cli build-essential m4 bison flex libuuid-devel qemu-img -y
            curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable --profile default -y
            export PATH="\$HOME/.cargo/bin:$PATH"
            git clone https://github.com/cloud-hypervisor/cloud-hypervisor.git
            if [ $? -ne 0 ]; then
              echo "Clone failed for cloud-hypervisor repo"
            fi

            cd cloud-hypervisor

            # Checkout the given commit of cloud-hypervisor repo and build
            # git checkout ${{ github.sha }}
            #if [ $? -ne 0 ]; then
            # echo "Checkout failed for: ${{ github.sha }}"
            # exit 1
            # fi
            if [ ${{matrix.RUNNER}} == 'INTEL-RUNNER-1' ]; then
              ${{matrix.BUILD_CMD_X86}} --release
            elif [ ${{matrix.RUNNER}} == 'ARM-RUNNER-1' ]; then
              ${{matrix.BUILD_CMD_AARCH64}} --release
            fi

          EOF